### ISSUE TITLE
Add image library to project (header, or CMake configuration)

### ISSUE THREAD

**Issue by jar2333** [jar2333/WFCpp#4]
Find one that can manipulate bitmaps (.bmp) with optional support for other formats :)

**Comment by jar2333** [comment]
The library must allow for splitting bitmaps, reading the color information pixelwise, reading and saving bitmaps to/from disk.

**Comment by jar2333** [comment]
https://github.com/sagefarrenholz/Blimp

**Comment by jar2333** [comment]
https://cimg.eu/

**Comment by jar2333** [comment]
http://www.partow.net/programming/bitmap/index.html

**Comment by jar2333** [comment]
The first and third look pretty good, the second a bit too complex for our needs.

**Comment by jar2333** [comment]
Third is header-only, first requires compiling to static library and linking, which has to be added to the CMake configuration. This should not be hard.

**Comment by Rico777** [comment]
https://easybmp.sourceforge.net
