### ISSUE TITLE
Tile class

### ISSUE THREAD

**Issue by jar2333** [jar2333/WFCpp#6]
A class which holds the data for a tile. Can be in-memory, as a resource handle for a file in the filesystem, whatever. Make sure that it can be queried for information relevant to the algorithm, i.e. for pixel data at the edges of each side, for example. Maybe have something like a 

```C++

class Tile {
public:
     bool matchesColors(Tile other, Direction d);
};
```

or something like that as the interface, and using whatever bitmap manipulation image library we are using to utilize the pixel color data in the implementation.

**Comment by jh4192** [comment]
```c++
class Tile {
    private string filePath;
    ImageObject getImageData();
    int getDimension();
}

```
